name: CI Markdown Profile

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  schedule:
    - cron: "1 0 * * *"

jobs:
  cron-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3      
        with:
         persist-credentials: false
         fetch-depth: 0
      - name: ðŸ’¡ Coding habits and activity - Recent activity charts
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.habits.charts.svg
          token: ${{ secrets.GIT_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: Asia/Jakarta
          output_action: none
          delay: 120
          user: lowlighter
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}          
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GIT_TOKEN }}
          user: ksatriow
          template: classic
          base: header, activity, community, repositories, metadata
          repositories_affiliations: owner, collaborator, organization_member
          config_timezone: Asia/Jakarta          
          
